# Docker Compose file for Resume Builder System
# Requires Docker v28+ and Docker Compose v2.36+

services:
  # Django Application
  web:
    build: .
    container_name: resume_django
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/static
    expose:
      - "8500"
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=resume_db
      - DB_USER=resume_user
      - DB_PASSWORD=resume_pass123
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - resume_network

  # MariaDB Database
  db:
    image: mariadb:11.4
    container_name: resume_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root_pass123
      MARIADB_DATABASE: resume_db
      MARIADB_USER: resume_user
      MARIADB_PASSWORD: resume_pass123
      MARIADB_CHARACTER_SET_SERVER: utf8mb4
      MARIADB_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 10s
    restart: unless-stopped
    networks:
      - resume_network

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: resume_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - resume_network

  # Adminer (Database Management)
  adminer:
    image: adminer:4.8.1
    container_name: resume_adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula
    ports:
      - "8085:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - resume_network

  # phpMyAdmin (Database Management - Alternative to Adminer)
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: resume_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: resume_user
      PMA_PASSWORD: resume_pass123
      UPLOAD_LIMIT: 50M
    ports:
      - "8086:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - resume_network

  # Portainer (Docker Management)
  portainer:
    image: portainer/portainer-ce:2.19.4
    container_name: resume_portainer
    command: -H unix:///var/run/docker.sock --http-enabled
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
      - "8000:8000"
    restart: unless-stopped
    networks:
      - resume_network

volumes:
  mariadb_data:
  static_volume:
  media_volume:
  portainer_data:

networks:
  resume_network:
    driver: bridge