# Generated by Django 5.0.1 on 2025-08-09 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('linkedin', models.URLField(blank=True, verbose_name='لینکدین')),
                ('github', models.URLField(blank=True, verbose_name='گیت\u200cهاب')),
                ('website', models.URLField(blank=True, verbose_name='وبسایت')),
                ('summary', models.TextField(blank=True, verbose_name='خلاصه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اطلاعات شخصی',
                'verbose_name_plural': 'اطلاعات شخصی',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='شرکت')),
                ('position', models.CharField(max_length=200, verbose_name='سمت')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_current', models.BooleanField(default=False, verbose_name='شغل فعلی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resumes.personalinfo')),
            ],
            options={
                'verbose_name': 'سابقه کاری',
                'verbose_name_plural': 'سوابق کاری',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200, verbose_name='مدرک')),
                ('field', models.CharField(max_length=200, verbose_name='رشته')),
                ('university', models.CharField(max_length=200, verbose_name='دانشگاه')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_current', models.BooleanField(default=False, verbose_name='در حال تحصیل')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resumes.personalinfo')),
            ],
            options={
                'verbose_name': 'تحصیلات',
                'verbose_name_plural': 'تحصیلات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مهارت')),
                ('level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته'), ('expert', 'حرفه\u200cای')], max_length=20, verbose_name='سطح')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.personalinfo')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان رزومه')),
                ('company_name', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('job_title', models.CharField(max_length=200, verbose_name='عنوان شغلی')),
                ('custom_summary', models.TextField(blank=True, verbose_name='خلاصه سفارشی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='resumes.personalinfo')),
                ('selected_educations', models.ManyToManyField(blank=True, to='resumes.education', verbose_name='تحصیلات انتخابی')),
                ('selected_experiences', models.ManyToManyField(blank=True, to='resumes.experience', verbose_name='سوابق انتخابی')),
                ('selected_skills', models.ManyToManyField(blank=True, to='resumes.skill', verbose_name='مهارت\u200cهای انتخابی')),
            ],
            options={
                'verbose_name': 'رزومه',
                'verbose_name_plural': 'رزومه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
