# Generated by Django 5.0.1 on 2025-08-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', '-start_date'], 'verbose_name': 'تحصیلات', 'verbose_name_plural': 'تحصیلات'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order', '-start_date'], 'verbose_name': 'سابقه کاری', 'verbose_name_plural': 'سوابق کاری'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'category', 'name'], 'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت\u200cها'},
        ),
        migrations.AddField(
            model_name='education',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='معدل'),
        ),
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='expected_salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حقوق مورد انتظار (تومان)'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متاهل'), ('divorced', 'مطلقه'), ('widowed', 'بیوه')], max_length=20, verbose_name='وضعیت تاهل'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='military_status',
            field=models.CharField(blank=True, choices=[('completed', 'پایان خدمت'), ('exempt', 'معافیت'), ('student_exempt', 'معافیت تحصیلی'), ('postponed', 'مهلت تحصیلی'), ('not_required', 'مشمول نمی\u200cباشد')], max_length=20, verbose_name='وضعیت سربازی'),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_category',
            field=models.CharField(choices=[('php_laravel', 'PHP / Laravel Developer'), ('python_django', 'Python / Django Developer'), ('wordpress', 'WordPress Developer'), ('frontend', 'Frontend Developer'), ('fullstack', 'Full-stack Developer'), ('mobile', 'Mobile Developer'), ('devops', 'DevOps Engineer'), ('data_science', 'Data Science'), ('ui_ux', 'UI/UX Designer'), ('project_manager', 'Project Manager'), ('other', 'سایر')], default='other', max_length=30, verbose_name='دسته\u200cبندی شغلی'),
        ),
        migrations.AddField(
            model_name='resume',
            name='target_salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حقوق مورد انتظار برای این موقعیت (تومان)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'برنامه\u200cنویسی'), ('web_frontend', 'فرانت\u200cاند وب'), ('web_backend', 'بک\u200cاند وب'), ('database', 'پایگاه داده'), ('mobile', 'موبایل'), ('devops', 'DevOps'), ('cms', 'سیستم مدیریت محتوا'), ('framework', 'فریم\u200cورک'), ('library', 'کتابخانه'), ('soft_skills', 'مهارت\u200cهای نرم'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='selected_skills',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, to='resumes.skill', verbose_name='مهارت\u200cهای انتخابی'),
        ),
    ]
