# Generated by Django 5.0.1 on 2025-08-09 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_education_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
