# Generated by Django 5.0.1 on 2025-08-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_remove_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='company_match_reason',
            field=models.TextField(blank=True, help_text='توضیح دهید که چرا شما برای این شرکت مفید هستید و این رزومه را متناسب با نیازهای آنها طراحی کرده\u200cاید', verbose_name='چرا این رزومه برای این شرکت مناسب است؟'),
        ),
        migrations.AddField(
            model_name='resume',
            name='copied_from',
            field=models.ForeignKey(blank=True, help_text='رزومه\u200cای که این رزومه از آن کپی شده', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.resume', verbose_name='کپی شده از'),
        ),
    ]
