# Generated by Django 5.0.1 on 2025-08-09 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_company_match_reason_resume_copied_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام منبع')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='شناسه URL')),
                ('website_url', models.URLField(blank=True, verbose_name='آدرس وبسایت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'منبع آگهی',
                'verbose_name_plural': 'منابع آگهی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='company_notes',
            field=models.TextField(blank=True, help_text='توضیحات و یادداشت\u200cهای شخصی درباره این شرکت', verbose_name='یادداشت\u200cهای شرکت'),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_ad_url',
            field=models.URLField(blank=True, help_text='لینک مستقیم صفحه آگهی استخدام', verbose_name='آدرس کامل صفحه آگهی'),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_source',
            field=models.ForeignKey(blank=True, help_text='منبعی که آگهی استخدام را در آن دیده\u200cاید', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.jobsource', verbose_name='منبع آگهی'),
        ),
    ]
