# Generated by Django 5.0.1 on 2025-08-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_jobsource_resume_company_notes_resume_job_ad_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='contract_type',
            field=models.CharField(choices=[('full_time', 'تمام وقت'), ('part_time', 'پاره وقت'), ('remote', 'دورکاری')], default='full_time', max_length=20, verbose_name='نوع قرارداد'),
        ),
    ]
