# Generated by Django 5.0.1 on 2025-08-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resume_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='language',
            field=models.CharField(choices=[('fa', 'فارسی'), ('en', 'انگلیسی'), ('de', 'آلمانی'), ('fr', 'فرانسوی'), ('ar', 'عربی')], default='fa', max_length=5, verbose_name='زبان رزومه'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='military_status',
            field=models.CharField(blank=True, choices=[('completed', 'پایان خدمت'), ('exempt', 'معافیت'), ('student_exempt', 'معافیت تحصیلی'), ('postponed', 'مهلت تحصیلی'), ('required', 'مشمول'), ('not_required', 'مشمول نمی\u200cباشد')], max_length=20, verbose_name='وضعیت سربازی'),
        ),
    ]
