# Generated by Django 5.0.1 on 2025-08-09 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_resume_language_alter_personalinfo_military_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'انگلیسی'), ('de', 'آلمانی'), ('fr', 'فرانسوی'), ('ar', 'عربی')], max_length=5, verbose_name='زبان')),
                ('degree', models.CharField(blank=True, max_length=200, verbose_name='مدرک ترجمه شده')),
                ('field', models.CharField(blank=True, max_length=200, verbose_name='رشته ترجمه شده')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='دانشگاه ترجمه شده')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='resumes.education')),
            ],
            options={
                'verbose_name': 'ترجمه تحصیلات',
                'verbose_name_plural': 'ترجمه\u200cهای تحصیلات',
                'unique_together': {('education', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ExperienceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'انگلیسی'), ('de', 'آلمانی'), ('fr', 'فرانسوی'), ('ar', 'عربی')], max_length=5, verbose_name='زبان')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='سمت ترجمه شده')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='شرکت ترجمه شده')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات ترجمه شده')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='resumes.experience')),
            ],
            options={
                'verbose_name': 'ترجمه سابقه کاری',
                'verbose_name_plural': 'ترجمه\u200cهای سوابق کاری',
                'unique_together': {('experience', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SkillTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fa', 'فارسی'), ('en', 'انگلیسی'), ('de', 'آلمانی'), ('fr', 'فرانسوی'), ('ar', 'عربی')], max_length=5, verbose_name='زبان')),
                ('name', models.CharField(max_length=100, verbose_name='نام ترجمه شده')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='resumes.skill')),
            ],
            options={
                'verbose_name': 'ترجمه مهارت',
                'verbose_name_plural': 'ترجمه\u200cهای مهارت',
                'unique_together': {('skill', 'language')},
            },
        ),
    ]
