# Generated by Django 5.0.1 on 2025-08-09 19:33

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_educationtranslation_experiencetranslation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='custom_summary',
            field=tinymce.models.HTMLField(blank=True, verbose_name='خلاصه سفارشی'),
        ),
    ]
