# Generated by Django 5.0.1 on 2025-08-09 19:40

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_alter_resume_custom_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='summary',
            field=tinymce.models.HTMLField(blank=True, verbose_name='خلاصه پیشفرض'),
        ),
    ]
