# Generated by Django 5.0.1 on 2025-08-09 19:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_alter_personalinfo_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job_ad_full_text',
            field=tinymce.models.HTMLField(blank=True, help_text='متن کامل آگهی استخدام برای مراجعه و بایگانی شخصی', verbose_name='متن کامل آگهی شرکت'),
        ),
    ]
