# Generated by Django 5.0.1 on 2025-08-09 20:06

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_resume_job_ad_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='توضیحات'),
        ),
    ]
