# Generated by Django 5.0.1 on 2025-08-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0013_resumeeducation_resumeexperience'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resumeexperience',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='resumeexperience',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resumeexperience',
            name='resume',
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date'], 'verbose_name': 'تحصیلات', 'verbose_name_plural': 'تحصیلات'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date'], 'verbose_name': 'سابقه کاری', 'verbose_name_plural': 'سوابق کاری'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name'], 'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت\u200cها'},
        ),
        migrations.RemoveField(
            model_name='education',
            name='order',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='order',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='order',
        ),
        migrations.DeleteModel(
            name='ResumeEducation',
        ),
        migrations.DeleteModel(
            name='ResumeExperience',
        ),
    ]
