# Generated by Django 5.0.1 on 2025-08-09 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0014_alter_resumeexperience_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.education')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume')),
            ],
            options={
                'verbose_name': 'تحصیلات رزومه',
                'verbose_name_plural': 'تحصیلات رزومه',
                'ordering': ['order'],
                'unique_together': {('resume', 'education')},
            },
        ),
        migrations.AlterField(
            model_name='resume',
            name='selected_educations',
            field=models.ManyToManyField(blank=True, through='resumes.ResumeEducation', to='resumes.education', verbose_name='تحصیلات انتخابی'),
        ),
        migrations.CreateModel(
            name='ResumeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.experience')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume')),
            ],
            options={
                'verbose_name': 'سابقه کاری رزومه',
                'verbose_name_plural': 'سوابق کاری رزومه',
                'ordering': ['order'],
                'unique_together': {('resume', 'experience')},
            },
        ),
        migrations.AlterField(
            model_name='resume',
            name='selected_experiences',
            field=models.ManyToManyField(blank=True, through='resumes.ResumeExperience', to='resumes.experience', verbose_name='سوابق انتخابی'),
        ),
    ]
